server.port=8081
spring.application.name=library-service

# Your local Postgres install from Sprint 3 — adjust username/password to match your own setup
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=postgres
spring.datasource.password=n3u3d4!

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true